packages:
  - 'packages/*'
allowBuilds:
  '@apollo/protobufjs': true
  '@parcel/watcher': true
  '@prisma/engines': true
  '@sentry/cli': true
  bcrypt: true
  esbuild: true
  prisma: true
  protobufjs: false
