import type { ParseSessionContext } from '../src/rest/voice';

export const TEST_CONTEXT: ParseSessionContext = {
    horses: [
        { id: 'cm3h1a2b3c4d5e6f7', name: 'Cheeto' },
        { id: 'cm3h2b3c4d5e6f7g8', name: 'Rosie' },
        { id: 'cm3h3c4d5e6f7g8h9', name: 'Rocky' },
        { id: 'cm3h4d5e6f7g8h9i0', name: 'Flash' },
    ],
    riders: [
        { id: 'cm3r1a2b3c4d5e6f7', name: 'Travis' },
        { id: 'cm3r2b3c4d5e6f7g8', name: 'Olivia' },
        { id: 'cm3r3c4d5e6f7g8h9', name: 'Paxton' },
        { id: 'cm3r4d5e6f7g8h9i0', name: 'Kelli' },
        { id: 'cm3r5e6f7g8h9i0j1', name: 'Jinny' },
    ],
    speakerName: 'Travis',
};

export const SAMPLE_TRANSCRIPTS: Record<string, string> = {
    'cheeto-groundwork': `I worked Cheeto on the ground today for 30 minutes on February 14th, oh February 15th, sorry, Sunday, February 15th. It went well for the most part, he was a little sore, so I decided not to do the in-hand work and just to, he looked short on the left front, and I couldn't tell if that was because he wasn't pushing behind or whether it was a problem up front, I picked out his feet, it didn't seem to be the issue, and he kind of worked out of it, so I just kind of pushed a little more and then he would work out of it, I don't know if he was just feeling sore from the previous day where we did the long lining work, however, you know, it was still kind of there near the end of the workout, we just did walk trot, that's basically it, when I pushed more from the trot he gave and he didn't look so bad, so that was good, and then I, since I had the Spanx Rider on and no reins, I went ahead and took my raincoat off, used my raincoat, I tied it to the top there for him, and he did deal with that flapping a little bit, a little spooky, but pretty good overall, and got more comfortable with it as time went on, it's kind of fluttering in the wind a little bit, rolls up, rolls down, and for the most part he's pretty good with it, he's a little bit more annoyed, you can tell he's a little more stompy when he's under pressure, he just gets a little bit more, shows those little annoyances, but other than that, pretty good, we'll see, I think that Kelly felt him be a little bit unsound a few days ago, so we'll see if this is a trend or is it something new, and keep an eye on it as we go forward here, it seems to seems to be he did get shod a few weeks ago or a week ago, I think he was shod before the round, but not shod, but his feet done, so maybe it's a little bit of tenderness from his feet, something for us to keep an eye on, see if that gets better.`,

    'cheeto-inhand': `I worked Cheeto for 30 minutes today. We did the in-hand work just in the arena. It was a little bit damp but not where the footing was excellent. We used the Spanish Rider and the Serrata and the whip, my in-hand whip. We did some to the left and to the right. Probably spent more time on the left than the right which went well. We just did a lot of halt walk transitions and really focused on getting up in the walk. And then instead of doing a halt to trot, which I don't think he's quite ready for, we started just doing a small trot while trying to stay up. And so just a little little bumps on the back of his rump to get him to trot and try to get the nice rhythm. Try to keep it as quick as I could. And then taps on the top to stay up which he came up pretty good. So it felt like today he was more up. And so then we could finally work on tucking. So we worked on tucking a little bit. He did have one moment where he kicked out pretty hard. It wasn't at me. It was directly back. Of course I got after him with a pretty good swat and it didn't happen again. It seemed a little uncalled for. I'm sure he was feeling I was pestering him but I certainly wasn't hitting him hard. After that we were still able to go back to our tucking and then even to the reaching underneath with the hind legs where I dropped a little lower. The moment he would reach underneath when I tapped I would stop. So one or two reaches and then I would just immediately stop there. We didn't do as many trot to halts. We mostly came down to the walk because I was just trying to get the tucking and then give him a reward. So that's kind of what our focus was. Overall I would say he was lighter in the serrata but I really focused on keeping him light. Any sense of heaviness and we would halt and take a step back right away. So we never really let that heaviness build or allow it to build. So it went pretty well there.`,

    'cheeto-flatwork': `Okay. I rode Cheeto for about 25 minutes on the flat in the arena. He hasn't been worked or ridden in a little while. So I mostly wanted to ensure that he felt forward and quick off of the leg, which he did. I was really pleased. He remembered the last several sessions. I forgot my spurs, but I would say he still moved away from the leg easily, which was good. I did not do any canner work this time. And sometimes going to the right, I didn't think he felt fully sound when I was trying to do some compression work and relaxation, but he was happy to stretch down with his nose down to the ground. He only peeked a little bit at the tarp, but didn't continue getting tense over it and was good on the upward transitions, downward transitions, he's still just heavy. So gotta work on that.`,

    'rosie-trail': `Olivia rode Rosie on a 45-minute trail ride just now. It went well. She rode alongside Cheeto and Kelly. They both went out there. They went past the stop sign about 1.75 miles total through the horses and everything. The mare was good. Got a little exciting when one of the horses cantered up, but Olivia worked good on her contact and keeping the mare's mind busy. The mare was spooky at a few things, which kind of made sense for the cross country. Pretty spooky at some of the large rocks, trouble walking up and so forth, but would go in and out of relaxation, but much more controllable than in the past.`,
};
